name: Build and Push Docker images

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag and push MySQL Docker image
        run: |
          docker build -t mysql -f Docker_mysql .
          docker tag mysql:latest ${{ steps.login-ecr.outputs.registry }}/mysql:latest
          docker push ${{ steps.login-ecr.outputs.registry }}/mysql:latest

      - name: Build, tag and push Webapp Docker image
        run: |
          docker build -t webapp -f Dockerfile .
          docker tag webapp:latest ${{ steps.login-ecr.outputs.registry }}/webapp:latest
          docker push ${{ steps.login-ecr.outputs.registry }}/webapp:latest
